// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxbLIOsqmHdooHiXFMUVLoKVj_TZKIGUE',
    appId: '1:88774670639:web:15e1e29f5981441c6a49da',
    messagingSenderId: '88774670639',
    projectId: 'flutter-registration-549d9',
    authDomain: 'flutter-registration-549d9.firebaseapp.com',
    storageBucket: 'flutter-registration-549d9.appspot.com',
    measurementId: 'G-CXJD1TFF8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWlavlxprW4aF-QMaFGOlefO38HOESo4g',
    appId: '1:88774670639:android:7f1567556d69f9d86a49da',
    messagingSenderId: '88774670639',
    projectId: 'flutter-registration-549d9',
    storageBucket: 'flutter-registration-549d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwUP8YfIEP2m4yyuve4cVZcWLdZWWSBLQ',
    appId: '1:88774670639:ios:b56f1ff5e5ca01286a49da',
    messagingSenderId: '88774670639',
    projectId: 'flutter-registration-549d9',
    storageBucket: 'flutter-registration-549d9.appspot.com',
    iosClientId: '88774670639-2t45cjurthf6t71sdt221pr5luuqgbck.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRegistrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwUP8YfIEP2m4yyuve4cVZcWLdZWWSBLQ',
    appId: '1:88774670639:ios:b56f1ff5e5ca01286a49da',
    messagingSenderId: '88774670639',
    projectId: 'flutter-registration-549d9',
    storageBucket: 'flutter-registration-549d9.appspot.com',
    iosClientId: '88774670639-2t45cjurthf6t71sdt221pr5luuqgbck.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRegistrationApp',
  );
}
